#!/bin/bash
git diff --quiet --cached && git diff --quiet || {
    echo run from a clean working copy and index >&2
    exit 1
}
git fetch --unshallow --no-tags https://github.com/hfg-gmuend/openmoji master:refs/tmp/openmoji/master
git read-tree -u --prefix art/openmoji/color/72x72/ FETCH_HEAD:color/72x72
HASH=$(git rev-parse FETCH_HEAD)
git commit -m "Updating openmoji to $HASH"
