#!/bin/bash
set -ueo pipefail
git diff --quiet --cached && git diff --quiet || {
    echo run from a clean working copy and index >&2
    exit 1
}
git fetch --depth 1 --no-tags https://github.com/hfg-gmuend/openmoji "${1:-master}"
git rm -rf art/openmoji
git read-tree -u --prefix art/openmoji/color/72x72/ FETCH_HEAD:color/72x72
HASH=$(git rev-parse FETCH_HEAD)
git commit -m "Updating openmoji to $HASH"
